[workspace]
resolver = "2"
members = [
    "rhombus",
    "rhombus-cli",
    "examples/standalone",
    "examples/plugin",
    "examples/external-plugin",
    "examples/shuttle",
    "examples/demo",
]
