# yaml-language-server: $schema=https://raw.githubusercontent.com/rhombusgg/rhombus-rs/main/schema.json
title: Rhombus
location_url: http://localhost:3000
database_url: file://rhombus.db
contact_email: admin@rhombus.gg
email:
  from: Rhombus <nextcloud@mbund.org>
in_memory_cache: 60
local_upload_provider:
  folder: uploads
divisions:
  - name: Open
    description: Open division for everyone
  - name: Undergraduate
    description: Undergraduate university students globally
    email_regex: ^.*.edu$
    requirement: Must verify a valid university .edu email address
  - name: OSU
    description: OSU undergraduate students
    email_regex: ^.*\.\d+@(buckeyemail\.)?osu\.edu$
    requirement: Must verify a valid OSU email address
discord:
  guild_id: 1160610137703186636
  client_id: 1160076447977848945
  author_role_id: 1198496803130183770
  first_blood_channel_id: 1240422645938389102
  support_channel_id: 1173026578385617010
  verified_role_id: 1170429782270431283
