version: "3"

tasks:
  dev:
    deps:
      - watch-standalone
      - watch-tailwindcss
    desc: Run cargo watch and tailwindcss concurrently

  watch-standalone:
    desc: Start cargo watch
    cmds:
      - cargo watch -x 'run -p standalone'

  watch-standalone-systemfd:
    desc: Start cargo watch using systemfd to not drop connections on restart
    cmds:
      - systemfd --no-pid -s http::3000 -- cargo watch -x 'run -p standalone'

  watch-tailwindcss:
    desc: Start Tailwind CSS in watch mode
    dir: rhombus
    silent: true
    cmds:
      - tailwindcss --input app.css -w -o static/tailwind.css
