[package]
name = "rhombus"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["cookie"] }
chrono = { version = "0.4.34", features = ["serde"] }
http-body-util = "0.1.0"
jsonwebtoken = "9.2.0"
listenfd = "1.0.1"
reqwest = { version = "0.11.24", features = ["native-tls-vendored", "json"] }
serde = { version = "1.0.196", features = ["derive"] }
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }
tera = "1.19.1"
time = "0.3.34"
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["compression-full", "fs"] }
tower-livereload = "0.9.2"
tower_governor = { version = "0.3.2", features = ["tracing"] }
tracing = "0.1.40"
