[package]
name = "rhombus"
version = "0.1.0"
edition = "2021"
description = "Next generation extendable CTF framework with batteries included"
authors = ["Mark Bundschuh <mark@mbund.dev>"]
license = "GPL-3.0-only"
repository = "https://github.com/rhombusgg/rhombus-rs"
homepage = "https://rhombus.gg"
keywords = ["web", "ctf"]

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.79"
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["cookie"] }
cached = { version = "0.49.2", features = ["async"] }
chrono = { version = "0.4.34", features = ["serde"] }
dotenvy = { version = "0.15.7", optional = true }
fluent = "0.16.0"
futures = { version = "0.3.30", optional = true }
intl-memoizer = "0.5.1"
jsonwebtoken = "9.2.0"
lazy_static = "1.4.0"
libsql = { version = "0.3.2", optional = true }
listenfd = "1.0.1"
minijinja = { version = "1.0.16", features = ["loader"] }
minijinja-embed = "1.0.15"
rand = "0.8.5"
reqwest = { version = "0.11.24", default-features = false, features = [
  "rustls-tls",
  "json",
] }
resvg = "0.40.0"
rust-embed = "8.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7.3", optional = true, features = [
  "tls-rustls",
  "runtime-tokio",
  "postgres",
  "chrono",
  "macros",
] }
time = "0.3.34"
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["compression-full", "fs"] }
tower-livereload = "0.9.2"
tower_governor = { version = "0.3.2", features = ["tracing"] }
tracing = "0.1.40"
unic-langid = { version = "0.9.4", features = ["unic-langid-macros"] }

[build-dependencies]
minijinja-embed = "1.0.15"

[features]
default = ["dotenv"]
postgres = ["dep:sqlx"]
libsql = ["dep:libsql", "dep:futures"]
dotenv = ["dep:dotenvy"]
all = ["dotenv", "postgres", "libsql"]

[dev-dependencies]
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.3.7", features = ["postgres"] }
