[package]
name = "rhombus"
version = "0.1.0"
edition = "2021"
description = "Next generation extendable CTF framework with batteries included"
authors = ["Mark Bundschuh <mark@mbund.dev>"]
license = "MPL-2.0"
repository = "https://github.com/rhombusgg/rhombus-rs"
homepage = "https://rhombus.gg"
keywords = ["web", "ctf", "http"]

[dependencies]
async-hash = "0.5.3"
async-trait = "0.1.80"
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["cookie"] }
chrono = { version = "0.4.38", features = ["serde"] }
config = "0.14.0"
dashmap = { version = "5.5.3", features = ["inline"] }
dotenvy = { version = "0.15.7" }
fluent = "0.16.1"
intl-memoizer = "0.5.1"
jsonwebtoken = "9.3.0"
lazy_static = "1.4.0"
lettre = { version = "0.11.7", default-features = false, features = [
  "tokio1-rustls-tls",
  "smtp-transport",
  "builder",
  "pool",
] }
mime_guess = "2.0.4"
minijinja = { version = "2.0.2", default-features = false, features = [
  "builtins",
  "multi_template",
  "macros",
  "speedups",
  "json",
] }
minijinja-embed = "2.0.2"
pin-project-lite = "0.2.14"
poise = "0.6.1"
rand = "0.8.5"
regex = "1.10.4"
reqwest = { version = "0.12.4", default-features = false, features = [
  "rustls-tls",
  "json",
] }
resvg = "0.41.0"
rust-embed = "8.3.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
serenity = { version = "0.12.1", features = ["chrono"] }
thiserror = "1.0.59"
time = "0.3.36"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["io"] }
tower = "0.4.13"
tower_governor = { version = "0.4.2" }
tower-http = { version = "0.5.2", features = ["compression-full", "fs"] }
tower-livereload = "0.9.2"
tracing = "0.1.40"
unic-langid = { version = "0.9.4", features = ["unic-langid-macros"] }
unicode-segmentation = "1.11.0"

futures = { version = "0.3.30", optional = true }
libsql = { git = 'https://github.com/tursodatabase/libsql.git', optional = true, features = [
  "encryption",
] }
listenfd = { version = "1.0.1", optional = true }
sqlx = { version = "0.7.4", optional = true, features = [
  "tls-rustls",
  "runtime-tokio",
  "chrono",
  "macros",
] }

[build-dependencies]
minijinja-embed = "2.0.2"
rustc_version = "0.4.0"

[dev-dependencies]
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.3.7", features = ["postgres"] }

[features]
default = ["libsql"]
postgres = ["dep:sqlx", "sqlx/postgres"]
mysql = ["dep:sqlx", "sqlx/mysql"]
libsql = ["dep:libsql", "dep:futures"]
systemfd = ["dep:listenfd"]
shuttle = []
testcontainers = []
internal = []
all = [
  "postgres",
  "mysql",
  "libsql",
  "systemfd",
  "shuttle",
  "testcontainers",
  "internal",
]
