[package]
name = "standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
rhombus = { path = "../../rhombus", features = ["libsql"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
